---
- name: Check the virtualization capabilities of all hosts
  hosts: all
  tasks:
    - name: Check for Virtualization in lscpu
      command: /usr/bin/lscpu
      register: lscpu_output
      changed_when: false
      failed_when: lscpu_output.stdout is defined and "Virtualization" not in lscpu_output.stdout
    - name: Output results
      debug:
        var: lscpu_output.stdout
