all:
  hosts:
    aggron.dondon.ninja:
    torchic.localdomain:
  children:
    gaming-rig:
      hosts:
        aggron.dondon.ninja:
          ansible_host: 192.168.194.61
          ansible_ssh_private_key_file: ~/.ssh/aggron
          ansible_python_interpreter: /usr/bin/python2
    test:
      hosts:
        torchic.localdomain:
          ansible_host: 127.0.0.1
